---
- hosts: devbox-host 
  gather_facts: no
  become: yes

  tasks:

  - name: Install the docker module for Ansible 
    pip:
      name:  docker
      state: present

  - name: Create mount volume for registry
    file:
      path: /tmp/registry
      state: directory

  - name: Deploy the local registry server
    docker_container:
        name: registry
        image: registry:2
        volumes:  /tmp/registry:/var/lib/registry
        ports:
        - "5000:5000"
        restart_policy: always
        state: started
        force_kill: yes
        interactive: yes
        restart: yes

  - name: Tag and push openr image to local registry
    docker_image:
      name: akshshar/openr-xr 
      repository: localhost:5000/openr-xr
      tag: latest
      push: yes
